[package]
name = "remote-music"
version = "0.1.0"
authors = ["Matteo De Carlo <matteo.dek@gmail.com>"]
build = "src/build.rs"

[build-dependencies]
serde_codegen = "0.6.11"
syntex = "0.26.0"

[dependencies]
rustful = "0.6"
rust-crypto = "0.2.34"
serde = "0.6.11"
serde_json = "0.6.0"
